language: java
#stages:
#- name: deploy
#    # require the branch name to be master (note for PRs this is the base branch name)
#    if: branch = deploy
deploy:
  provider: heroku
  app:
    deploy: heru-exp
  api_key:
    secure: "gl4F+llVkjlW1WX6G9stDhHhX4NVOzL3f08esNfDON9XqgM+nRwapMUifSe2GIE9SmYbJQkOv4XdGfwKwdzOTkHWli3uaq82BDLaH6U22/NT0M3+axHTcksKfWamu9a3TDCuRNA7hriXcnK0sfsiMfQYKpSukqrI808f4jGtQJ/VoKEC7NMm0u8swt5jiROzgf6ETxws08THoI5VJFmbBw1ef+ps3cOxZXTAPRYnaXDtk5PxBeC8ZNWpBN6Aao6Ix4VLtflFJ6Xe2wWGPMBbwQ1JPNMAMZqSCFgeGcQHGEC0YNFg5Fr0woQQuVfZkEU7+jLvZtC3KNN0Ds6RyhI/OdfBr8N1So4n/1rgXnZD7Ww37itP81H0bgnsOmUc4MtRp4OhLcgoE0xp4rm7FJItNoOrDr+SU8q0Ciint70EY31H5YOEX/uB1lb4Q5e1JpQUwkEnni1D5beuYovzGYywXcFue4PrzzeoGr165wJbOLvf6kIv2PpkDCQv356S0PvGIkageJAzAWo0K+441w/zJe02Td3gYi+2BwuGJ0VgWlKUG2GJf7FlD/Y/H1MofYvsWRbH70R9WvuK3eHe8S95Uzg5O1AaTN0G3HGucc8SFcsTqZzhVoUPzW2PPHXEWxPeQygTenjj/q00xZ7Zve4q/g6HdSva4TTw5IF6aanP5S8="

