language: java
stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = deploy
deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
